steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/fastapi-test-practice/fastapitestpractice", "."]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "fast-api-test-practice"
      - "--image"
      - "gcr.io/fastapi-test-practice/fastapitestpractice"
      - "--platform"
      - "managed"
      - "--region"
      - "europe-east1"
